require("dotenv").config()
const {
    HUBSPOT_ACCESS_TOKEN,
    DB_HOST,
    DB_USER,
    DB_PASSWORD,
    DB_NAME,
    DB_TABLE_CONTACTS,
    DB_COLUMNS_CONTACTS,
    DB_TABLE_CONTACTS_PAGINATION,
    DB_COLUMNS_CONTACTS_PROPERTIES,
    DB_TABLE_CONTACTS_PROPERTIES,
    DB_COLUMNS_CONTACTS_PAGINATION,
    DB_TABLE_DEALS,
    DB_COLUMNS_DEALS,
    DB_TABLE_DEALS_PAGINATION,
    DB_COLUMNS_DEALS_PAGINATION,
    DB_TABLE_BROKER_TEAMS,
    DB_COLUMNS_BROKER_TEAMS,
    DB_TABLE_USERS_PRIMARY_TEAM,
    DB_COLUMNS_USERS_PRIMARY_TEAM,
    DB_TABLE_USERS_SECONDARY_TEAM,
    DB_COLUMNS_USERS_SECONDARY_TEAM,
    DB_TABLE_OWNERS,
    DB_COLUMNS_OWNERS,
} = process.env

if (!HUBSPOT_ACCESS_TOKEN || !DB_HOST || !DB_USER || !DB_PASSWORD || !DB_NAME) {
    throw new Error("Essential environment variables are missing")
}
if (
    !DB_TABLE_CONTACTS ||
    !DB_TABLE_CONTACTS_PAGINATION ||
    !DB_TABLE_CONTACTS_PROPERTIES ||
    !DB_TABLE_DEALS ||
    !DB_TABLE_DEALS_PAGINATION ||
    !DB_TABLE_BROKER_TEAMS ||
    !DB_TABLE_USERS_PRIMARY_TEAM ||
    !DB_TABLE_USERS_SECONDARY_TEAM ||
    !DB_TABLE_OWNERS
) {
    throw new Error(`Essential MySQL table environment variables are missing`)
}
if (
    !DB_COLUMNS_CONTACTS ||
    !DB_COLUMNS_CONTACTS_PAGINATION ||
    !DB_COLUMNS_CONTACTS_PROPERTIES ||
    !DB_COLUMNS_DEALS ||
    !DB_COLUMNS_DEALS_PAGINATION ||
    !DB_COLUMNS_BROKER_TEAMS ||
    !DB_COLUMNS_USERS_PRIMARY_TEAM ||
    !DB_COLUMNS_USERS_SECONDARY_TEAM ||
    !DB_COLUMNS_OWNERS
) {
    throw new Error(`Essential MySQL columns environment variables are missing`)
}

export const CONFIG = {
    HUBSPOT_ACCESS_TOKEN,
    DB: {
        HOST: DB_HOST,
        USER: DB_USER,
        PASSWORD: DB_PASSWORD,
        NAME: DB_NAME,
        TABLES: {
            CONTACTS: DB_TABLE_CONTACTS,
            CONTACTS_PAGINATION: DB_TABLE_CONTACTS_PAGINATION,
            CONTACTS_PROPERTIES: DB_TABLE_CONTACTS_PROPERTIES,
            DEALS: DB_TABLE_DEALS,
            DEALS_PAGINATION: DB_TABLE_DEALS_PAGINATION,
            BROKER_TEAMS: DB_TABLE_BROKER_TEAMS,
            USERS_PRIMARY_TEAM: DB_TABLE_USERS_PRIMARY_TEAM,
            USERS_SECONDARY_TEAM: DB_TABLE_USERS_SECONDARY_TEAM,
            OWNERS: DB_TABLE_OWNERS,
        },
        COLUMNS: {
            CONTACTS: DB_COLUMNS_CONTACTS,
            CONTACTS_PAGINATION: DB_COLUMNS_CONTACTS_PAGINATION,
            CONTACTS_PROPERTIES: DB_COLUMNS_CONTACTS_PROPERTIES,
            DEALS: DB_COLUMNS_DEALS,
            DEALS_PAGINATION: DB_COLUMNS_DEALS_PAGINATION,
            BROKERS_TEAMS: DB_COLUMNS_BROKER_TEAMS,
            USERS_PRIMARY_TEAM: DB_COLUMNS_USERS_PRIMARY_TEAM,
            USERS_SECONDARY_TEAM: DB_COLUMNS_USERS_SECONDARY_TEAM,
            OWNERS: DB_COLUMNS_OWNERS,
        },
    },
}
